import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <h1>Header</h1>
      <body className={inter.className}>{children}</body>
    <h1>Footer</h1>
    </html>
  )
}
